apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: registry-svc
  labels:
    {{- include "istio-wasm.labels" . | nindent 4 }}
spec:
  hosts:
    - {{.Values.registry.domain}}
  addresses:
    - {{.Values.registry.host}}
  location: MESH_EXTERNAL
  ports:
    - number: 5000
      name: http
      protocol: HTTP
  resolution: STATIC
  endpoints:
    - address: {{.Values.registry.host}}
      ports:
        http: {{.Values.registry.port}}
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{- include "istio-wasm.fullname" }}-gateway
  labels:
    {{- include "istio-wasm.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{- include "istio-wasm.fullname" }}-vs
  labels:
    {{- include "istio-wasm.labels" . | nindent 4 }}
spec:
  hosts:
    - "*"
  gateways:
    - registry-gateway
  http:
    - match:
        - uri:
            prefix: /v2
          method:
            regex: "GET|PUT|POST|HEAD|OPTIONS|PATCH|DELETE"
      route:
        - destination:
            host: {{.Values.registry.domain}}
            port:
              number: {{.Values.registry.port}}


---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: {{- include "istio-wasm.fullname" }}-wasm
  labels:
    {{- include "istio-wasm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  url: oci://{{.Values.registry.domain}}:{{.Values.registry.port}}/{{.Values.wasm.image}}
  imagePullPolicy: IfNotPresent
  imagePullSecret: {{ include "istio-wasm.fullname" . }}
  phase: AUTHN
  pluginConfig:
    username: {{.Values.registry.username}}
    password: {{.Values.registry.password}}
